### ISSUE TITLE
Can't request DE2 demonstrator

### ISSUE THREAD

**Issue by maxineq96** [CruzerBlade9369/LocoOwnership#1]
When requesting the DE2 demonstrator via the `Work Train` Mode on the radio, it gives me one of my owned non-demonstrator locomotives. At least for the DE2 it did. It gave me the demonstrator one for the DH4 though, which is weird. Can't test with any other locos yet, as I either don't have them restored yet or don't own more than the demonstrator. Other than the demonstrators, I currently own 2 DE2's and 3 DH4's in this save.

I tried multiple times to request the DE2 demonstrator. Gives me the non-demonstrator one (the same one) every single time.

I did some further testing: I sold the DE2 that it was giving me, and it still gives me that exact locomotive, when requesting the demonstrator. Even when cleared with the radio, requesting the demonstrator brings the cleared locomotive back (including all of the installed gadgets that were on it).

**Comment by CruzerBlade9369** [comment]
I'll take a look, this is an odd one for sure.

**Comment by CruzerBlade9369** [comment]
Should be fixed in 1.4.0

**Comment by maxineq96** [comment]
Do I need to start a new save for this to be fixed? Because I just tried it and it is not fixed in my old save.

**Comment by CruzerBlade9369** [comment]
I've not been able to replicate it, can you send the save over?

**Comment by maxineq96** [comment]
It must be an issue with my save. I uninstalled Loco Ownership, loaded the save, and it still had the same behaviour.

Here's my save: [007_Career_8.zip](https://github.com/user-attachments/files/18967147/007_Career_8.zip)

[Custom Cargo](https://www.nexusmods.com/derailvalley/mods/907) and [Cruzer's Cargo Pack](https://www.nexusmods.com/derailvalley/mods/926) are required to load the save, or else the game resets and all my owned locos (including demonstrators) are despawned and the issue cannot be replicated.
`L-005` is my demonstrator DE2, currently sitting in `FRS`. However, when requesting it via the `Work Train` radio mode, I'm only ever getting `L-043`.  From the `Ownership` -> `Request` radio mode I can only select `L-043` or `L-099` (from the DE2s).

**Comment by CruzerBlade9369** [comment]
I've not been able to make a fix nor replicate it outside of your save. The issue seems to stand from your DE2 somehow being listed in both demonstrator and ownership lists. Selling the problematic loco from ownership might fix it, but I can't guarantee it not breaking the demonstrator list.
